### ISSUE TITLE
Investigate streaming issues involving Flash and Chrome

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#248]
Some background: [DI-121](https://lib-jira.ucsd.edu:8443/browse/DI-121)

Several people on that ticket were unable to stream _any_ DAMS audio objects using Chrome. Specific error is "Flash plugin failed to load". 
Firefox seems to be fine. 
(see image below from Cristela)

My machine manages to stream audio fine in Chrome. My specs are:
Chrome 54.0.2840.71 m (64-bit)
Flash Plugin Version (via chrome://plugins/): 23.0.0.205 (PPAPI)

![browserissue-screenshot-1](https://cloud.githubusercontent.com/assets/5183580/19786583/87d761c6-9c53-11e6-9fa5-12c13f5d7a7f.png)

**Comment by mcritchlow** [comment]
@VivianChu addressed some similar issues in the DMR project. She might some ideas on what might need to be done to address this in the DC app

**Comment by VivianChu** [comment]
@mcritchlow @remerjohnson - I got the same error message "Flash plugin failed to load" using chrome Version 54.0.2840.71 (64-bit).  However, it worked for older Chrome Version 49.0.2623.112 (64-bit).  The video object worked fine for me using Chrome because I updated it before when working on similar issue for DMR Video.  I think we could just update order of the audio files in the jwplayer config like video object.  For example 
//Video file
https://github.com/ucsdlib/damspas/blob/develop/app/views/dams_objects/_video_viewer.html.erb#L19-L21

//Audio file
https://github.com/ucsdlib/damspas/blob/develop/app/views/dams_objects/_audio_viewer.html.erb#L19-L20

What do you think?  Thanks

**Comment by mcritchlow** [comment]
Definitely worth trying out, thanks Vivian. I've added the ticket to the Sprint starting on Monday. I'll assign this to you @VivianChu

**Comment by VivianChu** [comment]
@mcritchlow @remerjohnson The problem has been fixed and deployed to QA environment.  I was able to stream the audio object and complex audio object using Chrome.  Here are the screen shot
![complexaudioobject](https://cloud.githubusercontent.com/assets/1864660/19977017/4eaa0226-a1af-11e6-8d6c-6004a9c67912.png)
![singleaudioobject](https://cloud.githubusercontent.com/assets/1864660/19977016/4ea72c22-a1af-11e6-8e9c-76e5643de874.png)
