### ISSUE TITLE
Share feature and Facebook: complex object images do not get pulled in

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#261]
When using the "AddThis" feature to share an image on a Facebook page, the following has been noted:

1. bb35511535: First page cover sheet is pulled in instead of the image.
![bb35511535_page1](https://cloud.githubusercontent.com/assets/4314914/20730999/32a58b98-b63d-11e6-827f-7e61418737a9.png)

2. bb4199286c: Image for complex object is not pulled in (blank).
![bb4199286c_image001](https://cloud.githubusercontent.com/assets/4314914/20731006/389bf1c2-b63d-11e6-9725-691403ea736e.png)

3. bb4029610p: Backside of postcard image (and front side) of the complex object is not pulled in.
![bb4029610p_backside](https://cloud.githubusercontent.com/assets/4314914/20731012/3cdd32be-b63d-11e6-8e5d-e8a9ebff5e44.png)

**Comment by gamontoya** [comment]
@dt-ucsd Is this something you can look into for starters? If it's way beyond what you can see, then we can assign to one of the developers.

**Comment by dt-ucsd** [comment]
In order to specify which image Facebook should use when sharing a page, we added Open Graph tags to the <head> of the HTML page. For example, to specify the image we are using the following:

<meta property="og:image" content="http://www.example.com/dc/object/abc123/_0_1.jpg" />

(More info on Open Graph Tags: https://developers.facebook.com/docs/sharing/webmasters#markup)

When I first reported this to you yesterday I thought we were not using them yet, but as it turns out we are. So the issue won’t be solved by adding them, rather after more digging I found that the URLs being added in for the images of complex objects are being constructed incorrectly (both Twitter and Open Graph). For example:

<meta name="twitter:image" content="http://library.ucsd.edu/dc/object/bb4029610p/__1_3.jpg">
<meta property="og:image" content="http://library.ucsd.edu/dc/object/bb4029610p/__1_3.jpg">

http://library.ucsd.edu/dc/object/bb4029610p/__1_3.jpg (Doesn’t work)
http://library.ucsd.edu/dc/object/bb4029610p/_1_3.jpg (Works)

Note the extra underscore in the filename in the broken link (“__1_3.jpg”). Simply have the devs correct the code that is generating the image filename in the URL and the issue should be resolved.

Let me know if you have any questions.

**Comment by gamontoya** [comment]
Per David:

- Note the extra underscore in the filename in the broken link (“__1_3.jpg”). Simply have the devs correct the code that is generating the image filename in the URL and the issue should be resolved.

**Comment by gamontoya** [comment]
@dt-ucsd Are you able to update this code yourself or **must** it be a developer?

**Comment by dt-ucsd** [comment]
I am working on the update. I'll have a PR out shortly.

**Comment by gamontoya** [comment]
@VivianChu @dt-ucsd Should I make sure this is working now on -prod?

**Comment by VivianChu** [comment]
@gamontoya Do you want me to make the release of damspas for staging and prod now?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Yes. So this change requires a deploy to prod, correct? Should I have someone test on staging first?

**Comment by VivianChu** [comment]
@gamontoya I will let you know when it get deployed to staging so you can test it first.
