### ISSUE TITLE
Permanently delete all objects from Yates collection

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damspas#339]
### Descriptive summary

Due to the multiple problems in the source MARC data for the [Peter Yates Collection](https://library.ucsd.edu/dc/collection/bb68616527) and how it was transformed, the objects ingested [were decided to require deletion](https://lisn.ucsd.edu/display/DLP/2017-05-09+Superpack%21+Meeting+notes).

https://library.ucsd.edu/dc/collection/bb68616527

### Rationale

We need to start over and re-export the entirety of the Roger records, and since we (DOMM) doesn't have an ETL process, it would be simpler to delete and start over.

**Comment by lsitu** [comment]
@remerjohnson As suggested by @mcritchlow, I think we can keep those ARKs by adding an additional column "ARK" in the Excel Input Stream with those ARKs listed to replace those records in Yates collection. 
However, when you have all those arks in the Excel Input Stream for reuse, I think we still can delete all objects in the collection for a clean restart of the ingest if you want.

**Comment by lsitu** [comment]
@GregReser I think if you add the same arks for each component, damsmanager will build the complex object for you. 
Yes, this will erase all the metadata in that ark so I think it should work if you are going to replace the metadata of those objects. The purpose of the ARK column is just serving as ark reusing but not batch editing since it'll erase all the metadata in that ARK. So if you are going to use it in other case, I would suggest delete all contents in those arks before moving forward with re-ingesting.

**Comment by GregReser** [comment]
@lsitu I'm not saying this is a bad idea, but it makes me wonder:

1. It's a lot of work to save 249 existing ARKs.  Why do we need to do that?
2. If we go to his effort, it would be nice to turn it into a process we could use in other cases.  For example, could it become an Excel re-import tool where for each Object ARK, all ARK contents are deleted then the new contents are written from the spreadsheet?

**Comment by lsitu** [comment]
@GregReser We did that all the time to save the ARKs because the ARKs are limited. I think you could just assign it to dev if it need lots of effort at your end to do that.
Yes, it make sense to do that for #2. However, it won't be an issue if we just want to replace the metadata of an existing object. The only issue is that some files could leave there in the filestore that we don't want if you use it for other purpose.

**Comment by GregReser** [comment]
@lsitu OK, let's try your original suggestion to reuse the Yates ARKs
You will generate a report of all Yates ARKS, including component ARKS?

**Comment by lsitu** [comment]
@GregReser I am on it now.

**Comment by lsitu** [comment]
@GregReser Attached yates-arks.txt is the ARKs for those 249 objects in Yates collection, and the component arks are also attached under each ark they belong to:
[yates-arks.txt](https://github.com/ucsdlib/damspas/files/1197609/yates-arks.txt)

Note: we only need to put the object ark (but not the component ark) in the components "ARK" cell and damsmanager will assemble the complex object for you with that ark.

Would you like me to delete all objects in the Yates collection now?

**Comment by GregReser** [comment]
@lsitu OK, so I really didn't need to ask for the component ARKs.

Thanks.

**Comment by lsitu** [comment]
@GregReser Do you want me to delete the Yates records now?

**Comment by GregReser** [comment]
Yes, you can delete all Yates objects now.

**Comment by lsitu** [comment]
@GregReser Here is the one with no component ARKs:
[yates-arks.txt](https://github.com/ucsdlib/damspas/files/1198696/yates-arks.txt)

**Comment by lsitu** [comment]
@GregReser I've deleted all objects in Yates collection on prod: https://library.ucsd.edu/dc/collection/bb68616527. It's ready for re-import now.
