### ISSUE TITLE
Documentation of access control logic

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damspas#541]
### Descriptive summary
There have been a number of cases where the access controls & restrictions are not working as expected.  There seem to be some additional logic in how access controls are implemented in the code.  We need full documentation of how final access level is determined in the DAMS, including metadata values which trigger default behavior, how overrides or exceptions are implemented (e.g. in what order), interactions between collection visibility and object settings, collection release implications, and any thing else which may impact object and collection visibility and access.

### Rationale
Objects which should be restricted are not, and based on the metadata alone, we are unable to reliably predict the behavior of objects within the system.

**Comment by gamontoya** [comment]
@jessicahilt I actually think someone is DOMM (@GregReser ?) should help document this, but punting your way for IT Dev assignment.

**Comment by arwenhutt** [comment]
@gamontoya DOMM does not need to be involved in this - we have lots of metadata documentation already, but what we are missing is how that metadata is actually used by the code.  So it's just that second piece, which is not something we can contribute to, that we need.  

After we get that information, we can then look at whether there are specific issues that need addressing, which would be collaborative.  But what we need now is just code logic documentation.

**Comment by lsitu** [comment]
@arwenhutt Do you have any examples that are not working as expected for access controls & restrictions? I think we may need to inspect what's the issue. I am wondering whether SOLR index is an issue since we haven't re-indexed all collections in SOLR when the UCSD IP/metadata-only features were deployed to prod earlier.

**Comment by gamontoya** [comment]
@arwenhutt Sounds good! Thanks for the info.

**Comment by arwenhutt** [comment]
@lsitu We've been troubleshooting individual objects and trying to guess what's happening for a long time now, but issues keep arising.  So what we really need is documentation of all the access control code/logic.  Thanks!

**Comment by lsitu** [comment]
@arwenhutt Got it! Where do you prefer to put the documentation?

**Comment by arwenhutt** [comment]
Awesome!  Thanks @lsitu! Wherever is convenient for you to put them is fine - LiSN or a shared google doc maybe?

**Comment by arwenhutt** [comment]
@lsitu I created a google doc:
https://docs.google.com/document/d/1tXST5uRi_09lWC-GKICVZ1vO9uKpUlWjY2mlv3E852U/edit
It's set to let anyone from UCSD with the link edit it - let me know if you have any problems!

**Comment by lsitu** [comment]
@arwenhutt Great! And I am able to access it. Thank you very much.

**Comment by lsitu** [comment]
@arwenhutt I've edited the google share doc https://docs.google.com/document/d/1tXST5uRi_09lWC-GKICVZ1vO9uKpUlWjY2mlv3E852U/edit for access control logic implementation. I think the flowcharts I added for decision making could be more straight forward for understanding the complicate logic under different scenarios: objects in a collection CLR with `visibility=[public | local | curator]`. Please let me know if you have any questions.
Just feel free to let me know if you have other thoughts regarding the format of the documentation that may help you understand it better. And if you see any cases/scenarios that doesn't meet your exceptions, I think we can adjust the logic a little bit. Thanks.

**Comment by arwenhutt** [comment]
@lsitu Thanks!  I just took a quick peek, but this should be very helpful.  The flow charts in particular are very easy to follow.  @GregReser or I might have some questions as we spend some time reviewing it.  

Thanks!

**Comment by lsitu** [comment]
@GregReser Yes. It's correct and the implementation of access control just utilizes the properties `copyrightStatus`. 

For **Other**
![image](https://user-images.githubusercontent.com/2430784/47684927-e3990f80-db91-11e8-9d4e-ef00184cf1d3.png) 
It also includes `copyrightStatus = "Unknown"`.

**Comment by GregReser** [comment]
@lsitu For a public collection, it looks like the path from Copyright Status UC Regents has no way to get to Public Access.  Should the No line from License/OtherRights Restricted go directly to Public Access?

Objects in a Public Collection
![image](https://user-images.githubusercontent.com/5453716/47755528-da747500-dc5b-11e8-9487-26877690d797.png)

**Comment by lsitu** [comment]
@GregReser I've updated the flowchart for objects in public collections. Thank you very much for your feedbacks.

**Comment by GregReser** [comment]
@lsitu for a Local Collection: 
![image](https://user-images.githubusercontent.com/5453716/47806428-fda03280-dcf6-11e8-9bcf-1bcf0b00df59.png)
Does "UCSD IP / Metadata-only" actually mean "UCSD IP / Public Metadata-only"?  That seems to be how it is currently working and the expected behavior as specified in https://github.com/ucsdlib/damspas/issues/356

One thing I found is that the above logic works for Copyright status Other, but not for UC Regents.  If the rights holder is UC Regents, the object is UCSD IP.  UC Regents objects generally have no License / OtherRights, so I'm not sure what is triggering them to be UCSD IP.  THe flowchart seems to say they would be Curator Access.

**Comment by lsitu** [comment]
@GregReser Yes, "UCSD IP / Metadata-only" is the feature in https://github.com/ucsdlib/damspas/issues/356.

For rights holder UC Regents, I think the flowchart is only showing the logic for the implementation. We may need to follow whether the object has the License / OtherRights elements in place to trigger the expected result. For example, if you add an embargoed/restricted license, then it's will be curator-only access as you mentioned. And if you also add OtherRights metadataDisplay, then you will get public metadata-only access. If the UC Regents held object is in a local collection, then it'll be UCSD IP only access. Let me know if see any objects that don't follow the logic in the flowchart. Thanks.

**Comment by GregReser** [comment]
@lsitu  The flowcharts show how CLR visibility determine object access, but objects can also determine CLR visibility, right?  A local CLR becomes visible if at least one object in the collection has a condition that makes it public, such as MetadataDisplay.

**Comment by lsitu** [comment]
@GregReser No. Objects won't be able to determine the CLR visibility. I think this is the rule we setup for incremental collection development and a collection won't be released  for public access until it's being reviewed and approved. So in a curator collection with `visibility='curator'`, all objects are curator, no matter what condition it is.

**Comment by GregReser** [comment]
@lsitu I have found that a local CLR is visible off campus if some objects are metadata-only.  I have done another test without metadata-only objects and the CLR was not visible off campus.

We don't have to solve this right now, I'm just trying determine what the logic is so we can consider if changes are needed.

I got these on results on staging from home (no VPN, not logged in)
![image](https://user-images.githubusercontent.com/5453716/47863401-71544500-ddb4-11e8-9d1c-ef668414a0f6.png)

**Comment by GregReser** [comment]
My screenshot above doesn't show it, but the CLR is also visible.
This was a different test and you can see the CLR in the results.
![image](https://user-images.githubusercontent.com/5453716/47864162-2dfad600-ddb6-11e8-8ba8-efb625c79bd1.png)

**Comment by lsitu** [comment]
@GregReser For local collections, I think we've discussed it in the passed to make it public viewable because of the `"UCSD IP / Metadata-only"` display the feature in #356 we need. If you think this shouldn't be the case, we could discuss and change it. But this is not the issue of determining the CLR visibility by the object view.

**Comment by GregReser** [comment]
I just had someone off campus confirm that this CLR is visible to the public.  The CLR visibility is "local"
https://librarytest.ucsd.edu/dc/collection/bd8212589g
As I said, we don't need to fix this right now, but if you can document what logic is causing it to display, that would be helpful.

![image](https://user-images.githubusercontent.com/5453716/47865222-dc077f80-ddb8-11e8-9267-5c6916c16b4f.png)

**Comment by GregReser** [comment]
@lsitu 

> For local collections, I think we've discussed it in the passed to make it public viewable because of the "UCSD IP / Metadata-only" display the feature in #356

OK, that's why I wanted to confirm: Objects can determine CLR visibility, at least that seems to be what's happening.  When I add a metadata-only object to a local CLR, the CLR becomes visible without having to manually edit the CLR metadata.  Can you add that to your flowchart?

This shows the multiple layers and directions of conditions we are trying to understand and document.

**Comment by lsitu** [comment]
@GregReser I think I can add a note for it. We make the CLR with `visibility=local` public discovery because of the requirements in https://github.com/ucsdlib/damspas/issues/356 for the `UCSD IP / Metadata-only` feature. And the local CLR will be discovery/visible without any objects in it. So it's not triggered by the object as you mentioned. This is only the CLR accessibility issue but not the object accessibility issue as the flowchart reflects.

**Comment by GregReser** [comment]
@lsitu seems it would be confusing to have a collection containing all local objects and a public CLR with no objects to view.  Maybe we don't have any of those.  Makes me wonder why we need a local CLR then.

**Comment by GregReser** [comment]
@lsitu file download allowed/not allowed is determined by file type and CLR visibility, correct?  For example, 
videos in a local collection are not downloadable
videos in a public collection are downloadable

**Comment by lsitu** [comment]
@GregReser I think local collection is necessary for those `UCSD IP / Metadata-only` collections in https://github.com/ucsdlib/damspas/issues/356.
For file downloads, I think it's quite complicate with the special requirements for video/audio and the `UCSD IP / Metadata-only` feature in the way that don't allow any downloads. I haven't document these kind of special access controls implemented in the damspas UI yet. But yes, I think I can add the paragraphs for file downloads as well.

**Comment by GregReser** [comment]
@lsitu Thanks, this gives us a clearer picture of how access controls work.  If we need to make changes to, we will open another ticket.

**Comment by lsitu** [comment]
@GregReser Thank you very much for your review. I've added another paragraph to clarify file downloads.
