### ISSUE TITLE
VRR PDF objects ingested as 'document-source' should link to a generated 'document-service' file in the object interface rather than a zoom

### ISSUE THREAD

**Issue by mdpeters** [ucsdlib/damspas#622]
### Descriptive summary

PDF objects ingested into the DAMS for use in the VRR with file use set as 'document-source', should generate a service PDF that is linked to the image preview in the object interface.

### Expected behavior

Preview image in the object interface should link to a service version of the PDF

### Actual behavior

Preview image tries to link to a zoomable image version of the object which was never generated because it's a PDF

### Examples

https://librarytest.ucsd.edu/dc/object/bd9919328s
https://librarytest.ucsd.edu/dc/object/bd4390265d

### Related work

ucsdlib/damsmanager#299
ucsdlib/damsmanager#332

**Comment by mcritchlow** [comment]
pinging @ucsdlib/domm for their thoughts on this

**Comment by GregReser** [comment]
I think you need to use document-service for PDFs.  document-source would be the raw scan(s) or perhaps a PDF if it were different somehow from the service version.

**Comment by remerjohnson** [comment]
Agreed with Greg that that is how the functionality is now, i.e. derivatives are not created. I know File Use in general was something we've wanted to revisit several times, so the question of what _should_ occur is still valid imo

**Comment by GregReser** [comment]
Yep, the current File Use values can create some unexpected behaviors.  Here's a list of current values and how they work: https://lisn.ucsd.edu/display/DOMM/File+use+controlled+value+list

**Comment by arwenhutt** [comment]
@mdpeters Sorry, I was replying in slack, didn't realize the conversation was happening here!  

It sounds like the question might be answered already, but to make sure we're all on the same page:
* To ingest a pdf file to be accessible via DAMS (with the image of the doc bringing up the pdf in a pdf viewer) then document-service is the file use value you want to use. 
* To ingest a pdf file that won't be accessible (i.e. the unwatermarked version) you can use document-source or document-alternate.
* If you want a trigger/hook for new automatic document processing on ingest, a new file use value would be the safest and easiest option.

**Comment by GregReser** [comment]
Agreed on point 3 - a new file use value for special processing on ingest would be better than relying on an existing property.

**Comment by mdpeters** [comment]
@mcritchlow I'm good with using a special value for processing source PDFs so that they generate a watermarked service PDF. Would make this a damsmanager issue rather than interface since it would be getting what it needs to display correctly.

**Comment by mcritchlow** [comment]
So am i right in understanding that we'd need this new file use value specifically to trigger the creation of the watermark derivative PDF? And, inversely, that if the watermarked pdfs are already generated, then they could be ingested normally as `source` (non watermark) and `service` (watermark)?

If so, I'm just wondering out loud if it's worth creating a new file use value rather than pre-generating the derivatives with a tool (provided by dams manager or otherwise). Curious what you all think.

**Comment by GregReser** [comment]
I have been thinking that it would be good to move some derivative processes out of ingest.  Mostly for very big files like video where a failure in derivative generation breaks the ingest (process times-out or objects have no files).  Another thing is video or PDF thumbnails - where the auto generated files are not useful and we end up manually replacing them.  On the other hand, still images are straightforward, so why add an extra step to something that works.  Could there be an option to manually generate derivatives in the ingest tool so we can supply our own in special cases?  Of course that means adding more columns to the spreadsheet and more chance for errors.  Oh, and developing a derivative generation process.

How often are going to watermark files?  Am I right that VRR is the first time?

**Comment by mdpeters** [comment]
I don't think we'd actually need a new file use value, it'd just simplify things. You could key off the only file being a `document-source` whose mimetype is `application/pdf`, is a Special Collections item, and is one of the locked down permission views (I realize that's a lot of ifs). 

Watermarks might become a pretty common thing if VRR takes off, we just don't know yet. To my knowledge the VRR is the first instance of us using them.

**Comment by mcritchlow** [comment]
> I have been thinking that it would be good to move some derivative processes out of ingest. Mostly for very big files like video where a failure in derivative generation breaks the ingest (process times-out or objects have no files)

I'm completely in agreement here. The entire ingest process, at least for batch ingest, would be significantly faster and more resilient. My impression is we often have the files far enough in advance of final metadata that this would be beneficial a significant percentage of the time.

> Another thing is video or PDF thumbnails - where the auto generated files are not useful and we end up manually replacing them.

Right. Or A/V files with special encoding/decoding issues, which i know has come up also. So rather than having an ffmpeg configuration that tries to suit every single possible combination (which isn't really possible), we could have a more sane default than we have now, but allow for customization if/when needed.

@GregReser - So at the moment, there is not a way to specify derivative files in the ingest template? Your comment makes me think there isn't, just want to clarify.

>  Could there be an option to manually generate derivatives in the ingest tool so we can supply our own in special cases?

Yeah, that's the general idea I've had in mind.

> I don't think we'd actually need a new file use value, it'd just simplify things. You could key off the only file being a document-source whose mimetype is application/pdf, is a Special Collections item, and is one of the locked down permission views (I realize that's a lot of ifs).

Yeah, that is a lot of ifs. Doable, but we already have lots of ifs as-is in the code :) I worry things like this become brittle as soon as the next use case comes around that breaks one of those conditionals.

It sounds like our trade off may be between a new file use value and allowing the ingest process to support specifying derivatives. The latter is certainly more work, but might also realize a number of other benefits for ingest in general. @jessicahilt @arwenhutt I'm curious what your thoughts are, and if you lean towards one approach or the other.

**Comment by arwenhutt** [comment]
@mcritchlow I agree there are potential benefits to rethinking ingest, but I think it would make more sense to consider some of this within the context of potential DAMS next system.

**Comment by mcritchlow** [comment]
@arwenhutt - yeah definitely. if ultimately it makes the most sense to create a special file use value to move ahead for now, then it is what it is :)

**Comment by arwenhutt** [comment]
@mcritchlow yeah, I don't know whether it is necessary or not.  Based on this thread, I'm not clear on what the specific goals or agreed on functionality around watermarking are.  

It seems like there are two approaches for watermarking:
1) manually create the watermarked version before ingest 
2) have the system do it automagically on ingest

For # 1 - I believe this is already possible by using two files on one component/object, 
* the watermarked with a file-use of "document-service", 
* the original with a file-use of "document-source" or "document-alternate"  

I am 95% confident that this would result in the browser behavior as described in the original question (saved original, watermarked version opens in acrobat).  And we've used this approach in the past for similar cases where we need to manually create derivatives for documents or data files.  This approach shouldn't require any metadata, system or workflow changes.

For # 2 - if it is a VRR requirement or an agreed deliverable to automate watermarking as part of the ingest process, then adding a new file-use value as the hook is _much_ preferable to trying to reuse an existing value and untangle/fix any unintentional affects on files currently in the dams that have that file-use value.  Also adding a new file-use value is pretty low effort/cost compared to the coding for the modifications to the derivative creation process itself.

And changing the whole ingest/derivative creation process just seems like a different conversation.

**Comment by arwenhutt** [comment]
Just a quick update on the approach used going into ucsdlib/damsmanager#332 
per VRR meeting 6/13 the trigger for watermarking will be a tick box on the DAMS manager excel import form - not a file use value.  More about the file-use values to be used with the watermarking at ucsdlib/damsmanager#332
