### ISSUE TITLE
Change font size of download button

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#638]
### Descriptive summary

Increase font size on the Download file button for components, make equivalent to the size of View file.

**Comment by mcritchlow** [comment]
There appear to be a few different component views, both of which differ from each other and the regular object view, which make what seems like a very trivial fix potentially a bit more involved, at least as far as ensuring consistency goes.

Consider examples from: https://library.ucsd.edu/dc/object/bb70335495

1.  Component display #1 
![pic-selected-190703-1121-19](https://user-images.githubusercontent.com/67506/60615780-cea9f700-9d84-11e9-8c03-441e2cbf6ab8.png)

2. Component display #2 
![pic-selected-190703-1121-34](https://user-images.githubusercontent.com/67506/60615793-d79ac880-9d84-11e9-91d8-504bd51e5617.png)

Then, we have a regular (non-compound) object: https://library.ucsd.edu/dc/object/bb70335495
![pic-selected-190703-1123-49](https://user-images.githubusercontent.com/67506/60615928-20eb1800-9d85-11e9-97d9-cdf86ca60241.png)

I'm assuming this ticket is referring to the first component display view. However, it occurs to me that we may want to consider making things more consistent. Thoughts?

**Comment by hjsyoo** [comment]
@mcritchlow Yes, I had Component display #1 and the non-compound object view in mind when reporting this enhancement request. I'm only requesting that the Download file buttons in both cases be made more prominent and equivalent to View file. I'm neutral on how this is done, but as a suggestion, what if on every display type:

- View file = orange
- Download file = blue
- Embed (for images) = white

Ideally, the View and Download are in the same position whenever they appear. Since Embed only shows up for images, maybe have it in a new position?

If this is all too much, though, enlarging the Download file buttons and giving them a button look (like View file) would be a win.

**Comment by mcritchlow** [comment]
I'd be curious to hear @dt-ucsd weigh in on this, if he has any free time to do so.

**Comment by dt-ucsd** [comment]
If I recall correctly, we de-emphasized ("link" button, off to the left) the download button to subtly encourage users to view the objects within the application. That's why it is the way it is. That said, there really isn't an issue with bumping up its emphasis if needs have changed.

The best approach would be to just change the Bootstrap class on the Download button to match the class of its sister View button. Also, change the position so that the Download button is just to the left of the View button rather that way off on the other side of the container.

*RE: Second example given above (Component display #2)*
For consistency, update "Download File" to read "Download file". Note the lowercase "f".

**Comment by gamontoya** [comment]
@mcritchlow Please proceed with: 

- _The best approach would be to just change the Bootstrap class on the Download button to match the class of its sister View button. Also, change the position so that the Download button is just to the left of the View button rather that way off on the other side of the container._

-  _Update "Download File" to read "Download file"._

**Comment by mcritchlow** [comment]
@gamontoya - will do, thanks!

**Comment by gamontoya** [comment]
@mcritchlow Same question here. What's holding this up from prod?

**Comment by mcritchlow** [comment]
https://github.com/ucsdlib/damsrepo/issues/92 - which is the QA reindexing to finish and those tickets reviewed. the reindexing has had to restart several times, which unfortunately has meant the ability to properly test has taken quite a while..

**Comment by lsitu** [comment]
@gamontoya / @mcritchlow Yes, it's still on-going with around 98,000 done now. Hopefully it could finish in the next two days.
