### ISSUE TITLE
Add "Sign In" link to 404 error page when accessing curator only objects

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#690]
### Descriptive summary

Investigate if it is possible to add a link to Sign In as a curator on 404 pages which are usually seen when trying to access an ARK that is curator only.

If so, it would be ideal to log in directly from the 404 error page and have it remember/retain the URL/ARK one was trying to access.

![dcError](https://user-images.githubusercontent.com/4314914/61500298-80e5df00-a97f-11e9-9143-08aa33d2b7ec.png)

### Rationale

Cristela et al. in the DL Operations Group stated that it's annoying to have to jump from page to page to access a curator only object if not already logged in.

**Comment by cgarciaspitz** [comment]
Any updates on this one?

**Comment by gamontoya** [comment]
@cgarciaspitz No. It needs to be reviewed and given a LOE by the DAMS Working Group. We meet next week.

**Comment by gamontoya** [comment]
@VivianChu Start this off as an R&D ticket to see what options there are. I think @mcritchlow might have some thoughts/input too.

**Comment by mcritchlow** [comment]
@gamontoya : @VivianChu and I just spoke and here are a few initial takeaways:

1. The page that you all are being sent to is a 404 page, which actually isn't technically correct. The 404 status code is about a page that is "Not Found". The correct error code for this is 403 "Forbidden". Our 403 page already has a `Sign In` link on it, so we're going to work on fixing this unless anyone sees that as problematic.

2. Our 404, 403, and 500 pages are actually static html pages. Which is the typical convention for web applications. Unfortunately, this means as currently designed, the pages themselves can't be easily taught what the "referring" page was in order to pass that along to the sign in code.

**Comment by gamontoya** [comment]
@mcritchlow @VivianChu:

1. Sounds good! How would I ever get/see a 403 in DC?
2. So are you saying we will continue to get a 403 page if someone shares a restricted object link with a curator not logged in?

**Comment by mcritchlow** [comment]
@gamontoya - here's a direct link: https://library.ucsd.edu/dc/403.html

**Comment by VivianChu** [comment]
@gamontoya - The update has been deployed to qa.  Could you review it?
For example
//Curator only object - 403 page
https://libraryqa.ucsd.edu/dc/object/bb76802909

//Not found object - 404 page
http://libraryqa.ucsd.edu/dc/object/bbxxxxxxxx

Thanks

**Comment by gamontoya** [comment]
@VivianChu Works great!

**Comment by gamontoya** [comment]
@VivianChu Yes, this can be pushed to prod. Do we need a release ticket?

**Comment by VivianChu** [comment]
@gamontoya - Yes, we need a release ticket.  I'll create a release ticket for it.  Do you want to include this work https://github.com/ucsdlib/damspas/issues/710 in this release if I get it done today? Thanks

**Comment by gamontoya** [comment]
Yes, and this release can happen on Monday so that gives you up until Friday to get https://github.com/ucsdlib/damspas/issues/710 done.

**Comment by VivianChu** [comment]
@gamontoya - The update has been deployed to production. Could you review it?
For example
//Curator only object - 403 page
https://library.ucsd.edu/dc/object/bb76802909

//Not found object - 404 page
http://library.ucsd.edu/dc/object/bbxxxxxxxx
